import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Nunito} from "next/font/google";
import Navbar from "@/app/components/navbar/Navbar";
import './layout.css'
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Airbnb | Luis Miguel Urbez',
  description: 'Generated by Luis Miguel Urbez',
}

const font = Nunito({
    subsets: ['latin']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Navbar/>
      {children}</body>
    </html>
  )
}

